config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/home" => "pages#home"
  get "/about" => "pages#about"

  # sign up
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  # sign in
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create", as: "log_in"
  
  # log out
  delete "logout", to: "sessions#destroy"
  
  # password
  get "password", to: "passwords#edit", as: "edit_password"
  patch "password", to: "passwords#edit"
  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  # logged in users only
  get "profile" => "profile#view"
  get "profile/edit" => "profile#edit", as: "edit_profile"
  patch "profile/edit" => "profile#update"

  get "series/new" => "series#new"
  get "series/:id" => "series#view"
  # post "series/new" => "series#create"

  get "issues/new" => "issues#new"
  get "issues/search" => "issues#search"
  post "issues/search" => "issues#get_results"
  get "issues/:id" => "issues#view"
  get "issues/:id/edit" => "issues#edit"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
	attribute :user
end

app/models/issue.rb
class Issue < ApplicationRecord
end

app/models/series.rb
class Series < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	# adds virtual attributes for authentication
	has_secure_password
	# validates email
	validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :set_current_user
	def set_current_user
		Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
	end
	def require_user_logged_in!
		redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
	end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
	before_action :require_user_logged_in!
	def new
	end
	def search; end
	def get_results
		url = "https://comicvine.gamespot.com/api/search/?format=json&api_key=#{ENV['COMICVINE_KEY']}&query=#{search_params['query']}&resources=issue"
		response = RestClient.get(url)
		responseObj = JSON.parse(response.body)
		@results = responseObj['results']
	end
	def view
		issueUrl = "https://comicvine.gamespot.com/api/issue/#{view_params['id']}?format=json&api_key=#{ENV['COMICVINE_KEY']}"
		
		issueResponse = RestClient.get(issueUrl)
		issueResponseObj = JSON.parse(issueResponse.body)
		@result = issueResponseObj['results']	

		volumeUrl = "#{@result['volume']['api_detail_url']}?format=json&api_key=#{ENV['COMICVINE_KEY']}"
		
		volumeResponse = RestClient.get(volumeUrl)
		volumeResponseObj = JSON.parse(volumeResponse.body)
		@volume = volumeResponseObj['results']
	end
	def edit; end
	def search_params
		params.permit(:query)
	end
	def view_params
		params.permit(:id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
		render template: "pages/home.html.erb"
	end

	def about
		render template: "pages/about.html.erb"
	end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	def new; end
	def edit
		# finds user with a valid token
		@user = User.find_signed!(params[:token], purpose: 'password_reset')
		rescue ActiveSupport::MessageVerifier::InvalidSignature
			redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
	end

	def create
		@user = User.find_by(email: params[:email])
		if @user.present?
			# send mail
			PasswordMailer.with(user: @user).reset.deliver_later
			# deliver_later is provided by ActiveJob
		end
		redirect_to root_path, notice: 'Please check your email to reset your password'
	end

	def update
		# updates user's password
		@user = User.find_signed!(params[:token], purpose: 'password_reset')
		if @user.update(password_params)
			redirect_to sign_in_path, notice: 'Your password was reset successfully. Please sign in.'
		else
			render :edit
		end
	end
	private
	def password_params
		params.require(:user).permit(:password, :password_confirmation)
	end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
	before_action :require_user_logged_in!
	def edit; end
	def update
		if Current.user.update(password_params)
			redirect_to root_path, notice: 'Password updated'
		else
			render :edit
		end
	end
	private
	def password_params
		params.require(:user).permit(:password, :password_confirmation)
	end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	before_action :require_user_logged_in!
	def view; end
	def edit; end
	def update
		if Current.user.update(profile_params)
			redirect_to root_path, notice: 'Your profile has been updated'
		else
			render :edit
		end
	end
	# private
	def profile_params
		params.require(:user).permit(:avatar, :display_name, :profile_text)
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			WelcomeMailer.with(user: @user).welcome_email.deliver_now
			session[:user_id] = @user.id
			redirect_to root_path, notice: 'Successfully created account'
		else
			render :new
		end
	end
	private
	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
	before_action :require_user_logged_in!
	def new; end
	def view; end
	# def create; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new; end

	def create
		user = User.find_by(email: params[:email])
		if user.present? && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path, notice: 'Logged in successfully'
		else
			flash.now[:alert] = 'Invalid email or password'
			render :new
		end
	end
	
	def destroy
		session[:user_id] = nil
		redirect_to root_path, notice: 'Logged Out'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/issues/get_results.html.erb
<div class="container">
	<h2 class="title is-2">Search Results</h2>

	<ul>
		<li>Page Results: <%= @pageResults %></li>
		<li>Total Results: <%= @totalResults %></li>
		<li>Limit: <%= @limit %></li>
	</ul>

	<table class="table is-fullwidth">
		<thead>
			<tr>
				<th>Select</th>
				<th>Cover Art</th>
				<th>Name</th>
				<th>Issue Number</th>
				<th>Cover Date</th>
			</tr>
		</thead>
		<tbody>
		 	<% @results.each do |result| %>
				<% 
				 	detail_url = result['api_detail_url']
					issue_path = detail_url.slice(0, detail_url.length - 1) 
					issue_id = issue_path.slice(issue_path.rindex('/') + 1, issue_path.length)
				%>
				<tr>
					<td><input type="checkbox" /></td>
					<td><img src="<%= result['image']['tiny_url'] %>" /></td>
					<td><%= result['volume']['name'] %></td>
					<td><a href="/issues/<%= issue_id %>"><%= result['issue_number'] %></a></td>
					<td><%= result['cover_date'] %></td>
				</tr>
			<% end %>
		</tbody>
	</table>
</div>

app/views/issues/new.html.erb
<div class="container">
	<h2 class="title is-2">New Issue</h2>
	<div class="level">
		<div class="level-left">
			<div class="level-item">
				<input id="series" type="text" class="input" placeholder="Search Query" />
			</div>
			<div class="level-item">
				<button class="button is-primary">Search</button>
			</div>
		</div>
	</div>
</div>

app/views/issues/search.html.erb
<div class="container">
	<h2 class="title is-2">Search Issues</h2>

	<div class="block">
		<%= form_with url: "/issues/search", method: :post do |form| %>
		 	<div class="field">
				<%= form.label :query, "Enter your search:" %>
				<%= form.text_field :query, class: 'input' %>
			</div>
			<div class="field">
				<%= form.submit "Search", class: "button is-primary" %>
			</div>
		<% end %>
	</div>
</div> 

app/views/issues/view.html.erb
<div class="container">
	<table class="table is-fullwidth">
		<thead>
			<tr>
				<td>Name</td>
				<td>Issue Number</td>
				<td>Cover Date</td>
				<td>Volume</td>
				<td>Publisher</td>
				<td>Actions</td>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td><%= @result['volume']['name'] %></td>
				<td><%= @result['issue_number'] %></td>
				<td><%= @result['cover_date'] %></td>
				<td><%= @volume['deck'] %></td>
				<td><%= @volume['publisher']['name'] %></td>
				<td><button class="button is-warning is-small">Add to collection</button></td>
		</tbody>
	</table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComicDB</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <nav class="navbar" aria-label="main navigation">
        <div class="navbar-brand">
          <a class="navbar-item" href="/home">Comic DB</a>
        </div>
        <div class="navbar-start">
        </div>
        <div class="navbar-end">
          <a class="navbar-item" href="/about">About</a>
          <% if Current.user %>
            <a class="navbar-item" href="/profile">
            	<% if Current.user.display_name != "" %>
                <%= Current.user.display_name %>
              <% else %>
                <%= Current.user.email %>
              <% end %>
            </a>
            <%= link_to 'Sign out', logout_path, method: :delete, class: 'navbar-item' %>
          <% else %>
            <a class="navbar-item" href="/sign_in">Sign In</a>
          <% end %>
        </div>
      </nav>
      <% if notice %>
      	<article class="message is-success">
          <div class="message-body">
            <p><%= notice %></p>
          </div>
        </article>
      <% end %>
      <% if alert %>
      	<article class="message is-danger">
          <div class="message-body">
            <p><%= alert %></p>
          </div>
        </article>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="about">
	<div class="section">
	 	<div class="container">
			<h1 class="title">About</h1>
			<h2 class="subtitle">Lorem ipsum dolor sit amet</h2>
		</div>
	</div>
</div>

app/views/pages/home.html.erb
<div class="home">
	<div class="section">
	 	<div class="container">
		 	<div class="block">
			<h1 class="title">Comic DB</h1>
			<h2 class="subtitle">Keep track of your comic books!</h2>
			</div>
			<% if !Current.user %>
				<div class="block">
					<p>
						<%= link_to 'Sign in', sign_in_path %>
						or
						<%= link_to 'Sign Up', sign_up_path %>
					</p>
				</div>
			<% else %>
				<div class="block">
					<a href="/issues/search" class="button is-primary">
						<span class="icon">
							<i class="fas fa-arrow-right"></i>
						</span>
						<span>New Issue</span>
					</a>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/password_resets/edit.html.erb
<div class="section">
	<div class="container">
		<h1 class="title">Reset Password</h1>

	<div class="columns">
	 	<div class="column is-one-quarter">
			<%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
				<div class="field">
					<%= f.label 'password', class: 'label' %>
					<%= f.password_field :password, required: true, class: 'input' %>
				</div>

				<div class="field">
					<%= f.label 'password_confirmation', class: 'label' %>
					<%= f.password_field :password_confirmation, required: true, class: 'input' %>
				</div>

				<div class="field">
					<%= f.submit 'Reset Password', class: 'button is-primary' %>
					<a href="/" class="button is-light">Cancel</a>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/password_resets/new.html.erb
<div class="section">
	<div class="container">
		<h1 class="title">Forgot your password?</h1>

	<div class="columns">
	 	<div class="column is-one-quarter">
			<%= form_with url: password_reset_path do |f| %>
				<div class="field">
					<%= f.label 'email', class: 'label' %>
					<%= f.text_field :email, required: true, class: 'input' %>
				</div>

				<div class="field">
					<%= f.submit 'Reset Password', class: 'button is-primary' %>
					<a href="/" class="button is-light">Cancel</a>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/series/new.html.erb
<div class="container">
	<h2 class="title is-2">New Series</h2>

	<div class="level">
		<div class="level-left">
			<div class="level-item">
				<input type="text" class="input" placeholder="Search series" />
			</div>
			<div class="level-item">
				<button class="button is-primary">Search</button>
			</div>
		</div>
	</div>
</div>

app/views/series/view.html.erb
<div class="container">
	<h2 class="title is-2">View Series</h2>
</div>